apiVersion: v1
kind: Service
metadata:
  name: hello-world-go-service
spec:
  type: NodePort
  selector:
    app: hello-world-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # 可选：指定端口（30000-32767）
